### ISSUE TITLE
cmake

### ISSUE THREAD

**Issue by smiyakos** [jvrc/tutorials#2]
産総研の宮腰と申します。

細かいですが。
Ubuntu14 をインストールしたのですが、
cmake は、入っていませんでした。
事前にインストールしておくべきものとして、
git等と同様に記載しておくと良いと思います。

以上、よろしくお願い致します。

**Comment by fkanehiro** [comment]
ご指摘ありがとうございます。
追記しておきました。

**Comment by smiyakos** [comment]
$B!!6b9-MM!"(B

$B!!5\9x$G$9!#(B

$B!!AaB.!"8fBP1~D:$-!"M-$jFq$&$4$6$$$^$9!#(B

$B!!0zB3$-!":3:Y$J7o$rO"Ej$9$k$+$b$7$l$^$;$s!#(B

$B!!E,Ev$K!"8fBP1~(B/$B%9%k!<(B/$B:o=|Ey$7$FD:$1$l$P(B

$BM-$jFq$$$G$9!#(B

$B!!0J>e!"$h$m$7$/$*4j$$CW$7$^$9!#(B

$B!!$G$O!#(B

---

$B:9=P?M(B: Fumio KANEHIRO notifications@github.com
$BAw?.F|;~(B: 2015$BG/(B12$B7n(B18$BF|(B 17:56
$B08@h(B: jvrc/tutorials
CC: $B5\9x@60l(B
$B7oL>(B: Re: [tutorials] cmake (#2)

$B$4;XE&$"$j$,$H$&$4$6$$$^$9!#(B
$BDI5-$7$F$*$-$^$7$?!#(B

##

**Comment by fkanehiro** [comment]
文字化けしてしまっているようです。

2015年12月21日 9:53 smiyakos notifications@github.com:

**Comment by smiyakos** [comment]
$B!!6b9-MM!"(B

$B!!5\9x$G$9!#(B

$B!!M>7W$J$_<j?t$r$_3]$1$7$F!"(B
$B?=$7Lu$"$j$^$;$s!#(B

$B!!Bg$7$?FbMF$G$O$J$/!"(B
$B8fBP1~$N$*Ni$H!":#8e$O!"(B
$BE,Ev$K%9%k!<$7$F2<$5$$!"(B
$B$H8@$&DxEY$NFbMF$G$7$?!#(B

$B!!0zB3$-!"$h$m$7$/$*4j$$CW$7$^$9!#(B

$B!!$G$O!#(B

$B!!(BKanehiro-sama,

  Miyakoshi-desu.

 Yokeina OTesuu-wo OKake-shite,
Moushiwake-arimasen.

 Taishita Naiyou-dehaNaku,
GoTaiou-no ORei to, Kongo-ha
Tekitou-ni Through-shite-kudasai,
toiu Teido-no Naiyou-deshita.

 HikiTsuzuki,
Yoroshiku ONegai-itashimasu.

 Deha.

$B!!6b9-MM!"(B

$B!!5\9x$G$9!#(B

$B!!AaB.!"8fBP1~D:$-!"M-$jFq$&$4$6$$$^$9!#(B

$B!!0zB3$-!":3:Y$J7o$rO"Ej$9$k$+$b$7$l$^$;$s!#(B
$B!!E,Ev$K!"8fBP1~(B/$B%9%k!<(B/$B:o=|Ey$7$FD:$1$l$P(B
$BM-$jFq$$$G$9!#(B

$B!!0J>e!"$h$m$7$/$*4j$$CW$7$^$9!#(B

$B!!$G$O!#(B

---

$B:9=P?M(B: Fumio KANEHIRO notifications@github.com
$BAw?.F|;~(B: 2015$BG/(B12$B7n(B21$BF|(B 9:57
$B08@h(B: jvrc/tutorials
CC: $B5\9x@60l(B
$B7oL>(B: Re: [tutorials] cmake (#2)

$BJ8;z2=$1$7$F$7$^$C$F$$$k$h$&$G$9!#(B

2015$BG/(B12$B7n(B21$BF|(B 9:53 smiyakos notifications@github.com:

> $B!!6b9-MM!" (B
> 
> $B!!5\9x$G$9!# (B
> 
> $B!!AaB.!"8fBP1~D:$-!"M-$jFq$&$4$6$$$^$9!# (B
> 
> $B!!0zB3$-!":3:Y$J7o$rO"Ej$9$k$+$b$7$l$^$;$s!# (B
> 
> $B!!E,Ev$K!"8fBP1~ (B/ $B%9%k!< (B/ $B:o=|Ey$7$FD:$1$l$P (B
> 
> $BM-$jFq$$$G$9!# (B
> 
> $B!!0J>e!"$h$m$7$/$*4j$$CW$7$^$9!# (B
> 
> $B!!$G$O!# (B
> 
> ---
> 
> $B:9=P?M (B: Fumio KANEHIRO notifications@github.com
> $BAw?.F|;~ (B: 2015 $BG/ (B12 $B7n (B18 $BF| (B 17:56
> $B08@h (B: jvrc/tutorials
> CC: $B5\9x@60l (B
> $B7oL> (B: Re: [tutorials] cmake (#2)
> 
> $B$4;XE&$"$j$,$H$&$4$6$$$^$9!# (B
> $BDI5-$7$F$*$-$^$7$?!# (B
> 
> ## 
> 
> Reply to this email directly or view it on GitHub<
> https://github.com/jvrc/tutorials/issues/2#issuecomment-165717304>.
> 
> ## 
> 
> Reply to this email directly or view it on GitHub
> https://github.com/jvrc/tutorials/issues/2#issuecomment-166169108.

##
