### ISSUE TITLE
誤植 (ディレクトリの位置)

### ISSUE THREAD

**Issue by smiyakos** [jvrc/tutorials#3]
産総研の宮腰です。

誤植のようです。

---

コントローラのソースコード

コード作成操作により、コントローラのソースコード一式がワークスペース内の領域「$HOME/workspace/RobotControllerRTC/」に生成されます。
コントローラのヘッダファイル

コントローラのヘッダファイルは以下になります。

```
$HOME/workspace/include/RobotControllerRTC/RobotControllerRTC.h
```

---

includeのディレクトリの位置が違うようです
(RobotControllerRTCの後)。

以上、よろしくお願い致します。

では。

**Comment by fkanehiro** [comment]
ご指摘ありがとうございます。
修正しました。
