### ISSUE TITLE
配布サンプルファイル

### ISSUE THREAD

**Issue by smiyakos** [jvrc/tutorials#4]
産総研の宮腰です。

　リンクだけではなく、配布するサンプルファイル群に
含めてみてはいかがでしょう。

例えば、
samples/tutorials/rtc
の中の辺りは候補になると思います。

---

雛形に追加するコードの差分(diff)は以下の通りです。

patch コマンドで差分を適用する場合は、こちらの 差分ファイル を取得してご利用ください。

1 --- RobotControllerRTC.cpp.orig      2015-12-03 11:11:10.351220019 +0900
2 +++ RobotControllerRTC.cpp   2015-12-03 11:13:11.787219170 +0900

---

　以上、よろしくお願い致します。

　では。

**Comment by fkanehiro** [comment]
ご提案ありがとうございます。
diffファイルをsamplesに追加し、そちらにも含まれている旨、チュートリアルに記載しました。
