### ISSUE TITLE
初心者向け補足説明

### ISSUE THREAD

**Issue by smiyakos** [jvrc/tutorials#5]
産総研の宮腰です。

(私を含む)初心者向けに補足説明を追加してみては
いかがでしょうか。

---

> RTCBuilderを用いて追加します。追加するデータポートのプロファイルは次のようになります。

RTCBuilderを用いて追加します。[RobotControllerRTC]の[データポート]タブから、追加([Add])するデータポートのプロファイルは次のようになります。
# 地の文で「追加」と書いてあるところは、[生成]の場合と[Add]の場合とあるようです。

---

> データポートを追加し、再度コード生成を行ったら、ビルドができることを確認しておきます。

データポートを追加し、[基本]タブから再度コード生成([コード生成]と[Generate])を行ったら、ビルド(buildディレクトリにてmake)ができることを確認しておきます。

---

> コントローラのヘッダファイルはいかのようになります。

コントローラのヘッダファイル(RobotControllerRTC.h)は以下のようになります。
(ファイルは ~/workspace/RobotControllerRTC/include/ 内)

---

> コントローラのソースコードは以下になります。

コントローラのソースコード(RobotControllerRTC.cpp)は以下になります。
(ファイルは samples/tutorials/rtc/ 内 RobotTorqueControllerRTC.cpp を
workspace/RobotControllerRTC/src/ 内にコピーしてファイル名を変更する等
して下さい)

---

> コントローラのビルド
> 
> コントローラの実装ができたので、再度makeをし、前節と同じ場所にRTCをインストールします。

コントローラのビルド

コントローラの実装ができたので、buildディレクトリ内にて再度makeをし、前節と同じ場所にRTCをインストールします。
# 現状、色々エラーが出てしまうようです。

---

　以上、よろしくお願い致します。

　では。

---

**Comment by fkanehiro** [comment]
ありがとうございます。
コメントの幾つかを反映させました。
またチュートリアルの各ステップで作成するコントローラを従来はファイル名やクラス名を分けて1つのディレクトリに置いていたのですが、これだとご提案のようにファイルを上書きして使う、ということができないので、各ステップでのコントローラのソース一式を別のディレクトリに収録するようにしました。samplesも更新をお願い致します。

**Comment by smiyakos** [comment]
$B!!6b9-MM!"(B

$B!!5\9x$G$9!#(B

$B!!8fBP1~D:$-!"M-$jFq$&$4$6$$$^$9!#(B

$B!!:Y$+$$$N$G$9$,!"(B

$B%3%s%H%m!<%i$N%=!<%9%3!<%I(B(RobotControllerRTC.cpp)$B$O0J2<$K$J$j$^$9!#(B($B%U%!%$%k$O(B samples/tutorials/rtc/RobotControllerRTC3/src/RobotTorqueControllerRTC.cpp$B$K<}O?$5$l$F$$$^$9(B)

$B$N%U%!%$%kL>$O!"(B

$B%3%s%H%m!<%i$N%=!<%9%3!<%I(B(RobotControllerRTC.cpp)$B$O0J2<$K$J$j$^$9!#(B($B%U%!%$%k$O(B samples/tutorials/rtc/RobotControllerRTC3/src/RobotControllerRTC.cpp$B$K<}O?$5$l$F$$$^$9(B)

$B$G$O$J$$$+!"$H;W$$$^$9!#(B

$B!!:Q$_$^$;$s!#;d$+$iAw$C$?%3%a%s%H$O!"8E$$%U%!%$%kL>$K9g$o$;$F$"$C$?$N$G!#(B

$B!!0J>e!"$h$m$7$/$*4j$$CW$7$^$9!#(B

$B!!$G$O!#(B

---

$B:9=P?M(B: Fumio KANEHIRO notifications@github.com
$BAw?.F|;~(B: 2015$BG/(B12$B7n(B23$BF|(B 16:48
$B08@h(B: jvrc/tutorials
CC: $B5\9x@60l(B
$B7oL>(B: Re: [tutorials] $B=i?4<T8~$1JdB-@bL@(B (#5)

$B$"$j$,$H$&$4$6$$$^$9!#(B
$B%3%a%s%H$N4v$D$+$rH?1G$5$;$^$7$?!#(B
$B$^$?%A%e!<%H%j%"%k$N3F%9%F%C%W$G:n@.$9$k%3%s%H%m!<%i$r=>Mh$O%U%!%$%kL>$d%/%i%9L>$rJ,$1$F(B1$B$D$N%G%#%l%/%H%j$KCV$$$F$$$?$N$G$9$,!"$3$l$@$H$4Ds0F$N$h$&$K%U%!%$%k$r>e=q$-$7$F;H$&!"$H$$$&$3$H$,$G$-$J$$$N$G!"3F%9%F%C%W$G$N%3%s%H%m!<%i$N%=!<%90l<0$rJL$N%G%#%l%/%H%j$K<}O?$9$k$h$&$K$7$^$7$?!#(Bsamples$B$b99?7$r$*4j$$CW$7$^$9!#(B

## 

Reply to this email directly or view it on GitHubhttps://github.com/jvrc/tutorials/issues/5#issuecomment-166828924.

[https://avatars2.githubusercontent.com/u/16345550?v=3&s=400]https://github.com/jvrc/tutorials/issues/5#issuecomment-166828924

$B=i?4<T8~$1JdB-@bL@(B * Issue #5 * jvrc/tutorials<https://github.com/jvrc/tutorials/issues/5#issuecomment-166828924>
github.com
$B;:Am8&$N5\9x$G$9!#(B ($B;d$r4^$`(B)$B=i?4<T8~$1$KJdB-@bL@$rDI2C$7$F$_$F$O(B $B$$$+$,$G$7$g$&$+!#(B RTCBuilder$B$rMQ$$$FDI2C$7$^$9!#DI2C$9$k%G!<%?%]!<%H$N%W%m%U%!%$%k$O<!$N$h$&$K$J$j$^$9!#(B RTCBuilder$B$rMQ$$$FDI2C$7$^$9!#(B[RobotControllerRTC]$B$N(B[$B%G!<%?%]!<%H(B]$B%?%V$+$i!"DI2C(B([Add])$B$9$k%G!<%?%]!<%H$N%W%m%U%!%$%k$O<!$N$h$&$K$J$j$^$9!#(B $BCO$NJ8$G!V(B...

**Comment by fkanehiro** [comment]
すみませんがまた化けてしまっているようです。

**Comment by smiyakos** [comment]
Kanehiro-sama,

 Miyakoshi-desu.

# Mojibake, Naze-deshou-ne...

Old: samples/tutorials/rtc/RobotControllerRTC3/src/RobotTorqueControllerRTC.cpp

New: samples/tutorials/rtc/RobotControllerRTC3/src/RobotControllerRTC.cpp

 Ijhou-desu.

 Deha.

---

$B:9=P?M(B: Fumio KANEHIRO notifications@github.com
$BAw?.F|;~(B: 2015$BG/(B12$B7n(B24$BF|(B 21:55
$B08@h(B: jvrc/tutorials
CC: $B5\9x@60l(B
$B7oL>(B: Re: [tutorials] $B=i?4<T8~$1JdB-@bL@(B (#5)

$B$9$_$^$;$s$,$^$?2=$1$F$7$^$C$F$$$k$h$&$G$9!#(B

## 

Reply to this email directly or view it on GitHubhttps://github.com/jvrc/tutorials/issues/5#issuecomment-167106403.

$B=i?4<T8~$1JdB-@bL@(B * Issue #5 * jvrc/tutorials<https://github.com/jvrc/tutorials/issues/5#issuecomment-167106403>
github.com
$B;:Am8&$N5\9x$G$9!#(B ($B;d$r4^$`(B)$B=i?4<T8~$1$KJdB-@bL@$rDI2C$7$F$_$F$O(B $B$$$+$,$G$7$g$&$+!#(B RTCBuilder$B$rMQ$$$FDI2C$7$^$9!#DI2C$9$k%G!<%?%]!<%H$N%W%m%U%!%$%k$O<!$N$h$&$K$J$j$^$9!#(B RTCBuilder$B$rMQ$$$FDI2C$7$^$9!#(B[RobotControllerRTC]$B$N(B[$B%G!<%?%]!<%H(B]$B%?%V$+$i!"DI2C(B([Add])$B$9$k%G!<%?%]!<%H$N%W%m%U%!%$%k$O<!$N$h$&$K$J$j$^$9!#(B $BCO$NJ8$G!V(B...

**Comment by fkanehiro** [comment]
ありがとうございます。
修正しました。
