### ISSUE TITLE
復習する場合

### ISSUE THREAD

**Issue by smiyakos** [jvrc/tutorials#6]
産総研の宮腰です。

　受講した後、復習にこのテキストを遣う事はある、
と思います。
　初回の起動の場合と、２回目以降の起動の場合とで、
必要なコマンドや出てくる画面等が違っている場合があり、
戸惑う場合があります。

---

> git clone https://github.com/jvrc/samples

---

> Eclipseが起動すると、ワークスペースの場所を尋ねられます。

(２度目以降の起動等、ディレクトリが既に作成されている方はxxに進んで下さい。)

xxは、「右上の「パースペクティブを開く」ボタンを押し、」辺り?

---

　また、復習をする場合には、以前やった状態まで、
すぐに戻れると便利だと思います。

各章の最後の方に

---

> サンプルプロジェクトについて
> 
> このサンプルのプロジェクトファイルは「サンプルファイルのインストール」でダウンロードしたリポジトリの「samples/tutorials/cnoid/sample1.cnoid」に保存されています。

---

等と記述されている箇所がありますが、
復習する人向けには、
例えば、

---

> シミュレーションの実行
> 
> この節ではシミュレーションプロジェクトを作成する方法について解説します。

---

の辺りに、

---

(この章の設定ファイルは「samples/tutorials/cnoid/sample1.cnoid」に保存されていますので、復習される方は、ファイルを読み込んで下さい。

---

と言った感じの記述があると、親切かもしれません。

御検討頂けると有難いです。

　以上、よろしくお願い致します。

**Comment by fkanehiro** [comment]
ありがとうございます。
openrtpの起動時の説明部分、各チュートリアルでプロジェクトファイルを読み込む部分、最後に保存する部分等に追記させて頂きました。
