### ISSUE TITLE
復習する場合

### ISSUE THREAD

**Issue by smiyakos** [jvrc/tutorials#7]
産総研の宮腰です。

　大変お世話になっております。

　ちょっとくどい書き方になるかもしれませんが、
以下のような書き方は如何でしょう。

---

コントローラのヘッダファイル(RobotControllerRTC.h)は以下のようになります。(ファイルは ~/workspace/RobotControllerRTC/include/ 内)

コントローラのヘッダファイル(RobotControllerRTC.h)は以下のようになります。
(ファイルは ~/workspace/RobotControllerRTC/include/ 内にあります。
サンプルファイルは samples/tutorials/rtc/RobotControllerRTC3/include/RobotControllerRTC.h に収録されています)

---

コントローラのソースコード(RobotControllerRTC.cpp)は以下になります。(ファイルは samples/tutorials/rtc/RobotControllerRTC3/src/RobotControllerRTC.cppに収録されています)

コントローラのソースコード(RobotControllerRTC.cpp)は以下になります。
(ファイルは ~/workspace/RobotControllerRTC/src/ にあります。
サンプルファイルは samples/tutorials/rtc/RobotControllerRTC3/src/RobotControllerRTC.cpp に収録されています)

---

...そこでsrc/CMakeLists.txtを次のように編集します。

...そこでsrc/CMakeLists.txtを次のように編集します。
(サンプルファイルは samples/tutorials/rtc/RobotControllerRTC3/src/CMakeLists.txt に収録されています)

---

　御検討頂けますと有難いです。

　以上、よろしくお願い致します。

**Comment by fkanehiro** [comment]
ありがとうございます。反映させました。
