### ISSUE TITLE
ファイルの保存場所

### ISSUE THREAD

**Issue by smiyakos** [jvrc/tutorials#8]
産総研の宮腰です。

　大変お世話になっております。

---

SampleMotion の子供に motion があるので、これを選択し名前を付けて保存ボタンを押します。

SampleMotion の子供に motion があるので、これを選択し、[ファイル][名前を付けて選択アイテムを保存]します。

---

ファイル名はRobotPattern.yamlとし、コントローラが参照するChoreonoidの共有ディレクトリ、/usr/share/choreonoid-1.5/motionに置いておきます。

---

　ファイルが保存できないようです。
　パーミッションの関係だと思います。

　以上、よろしくお願い致します。

**Comment by fkanehiro** [comment]
ありがとうございます。
更新しました。

**Comment by smiyakos** [comment]
金広様、

　宮腰です。

　迅速な御対処、有り難うございます。

　保存できなかったのですが、

> BodyMotionItem "motion" を "/usr/share/choreonoid-1.5/motion/RobotPattern.yaml" に保存中-> 完了!

と言う「メッセージ」が出ていたので、
エラー判定のレベル設定とも絡むかもしれませんが、
併せて御報告致します。

　以上、よろしくお願い致します。
