### ISSUE TITLE
チェックについて

### ISSUE THREAD

**Issue by smiyakos** [jvrc/tutorials#9]
産総研の宮腰です。

choreonoid
を立ち上げ、直後に、
sample3.cnoid
を読み込んでみたところ、
以下のようなworningが出ました。

---

プロジェクトファイル"/home/smiyakos/Cnoid/samples/tutorials/cnoid/sample3.cnoid"を読み込み中…
WorldItem "World" を読み込み中
BodyItem "JVRC" を読み込み中
OpenHRP モデルファイル "/home/smiyakos/Cnoid/samples/tutorials/JVRC-1/main.wrl" を読み込み中
-> 完了!
Warning: Mismatched size of the stored initial joint positions for JVRC
BodyRTCItem "BodyRTC" を読み込み中
RTC "RobotControllerRTC" を "/usr/lib/choreonoid-1.5/rtc/RobotControllerRTC.so" から生成しました。
RTC "JVRC" を生成しました。
PoseSeqItem "PoseSeq" を読み込み中
ポーズ列 "/home/smiyakos/Cnoid/samples/tutorials/cnoid/SampleMotion.pseq" を読み込み中
-> 完了!
BodyItem "Floor" を読み込み中
OpenHRP モデルファイル "/usr/share/choreonoid-1.5/model/misc/floor.wrl" を読み込み中
-> 完了!
AISTSimulatorItem "AISTSimulator" を読み込み中
6 / 6 のアイテムが読みこまれました。
プロジェクト "/home/smiyakos/Cnoid/samples/tutorials/cnoid/sample3.cnoid" の読み込みに成功しました。
RTCの設定をしています。
ExtTrigExecutionContextを検出しました。
JVRC:q --> RobotControllerRTC0:q 接続しています....
接続しました。
JVRC:u_in <-- RobotControllerRTC0:u 接続しています....
接続しました。
AISTSimulatorによるシミュレーションを開始しました。
AISTSimulatorによるシミュレーションが1.229秒時点で終了しました。
計算時間: 3.319 [s], 計算時間 / シミュレーション時間 = 2.70057

---

無視して、実行(シミュレーション)してみたところ、
直立不動の体勢のまま、コマのように数回転して、
倒れてしまいました。

何か設定が必要でしたでしょうか。

---

と言う報告を書いた後、

「アイテム」「motion」

にチェックを入れたら、意図したように
シミュレーション結果が出てきました。

　さて、以下、やや八つ当たり気味ですが、

---
1. 読み込んだ動作データを再生するには、それらを選択しておく必要があります。
   （複数物体がある場合は、全てのBodyMotionアイテムを選択します）

---

モデルを読み込んだだけではロボットは表示されません。 「アイテム」と書かれたリストのJVRC-1にチェックを入れてください。 すると、以下のようにロボットが表示されるはずです。

---

の辺りでも感じたのですが、
読み込み等を行った場合の後の状態は、
デフォルトでチェックが入るようになっている方が、
直感的なのではないか(少なくとも私のような初心者には)、
と思います。

一つの意見として、ご考慮頂ければ有難いです。

　以上、よろしくお願い致します。

**Comment by fkanehiro** [comment]
関連する議論が、
s-nakaoka/choreonoid#50
fkanehiro/choreonoid-editor#2
にあるのでそちらを御覧ください。
なお、sample3.cnoidを開いてシミュレーションがおかしいのはBodyRTCアイテムにチェックが入っていないためです。チュートリアルの本文中にはチェックを入れることが書いてあるのですが、sample3.cnoidにそれが反映されていなかったので反映しておきました。

**Comment by smiyakos** [comment]
$B!!6b9-MM!"(B

$B!!5\9x$G$9!#(B

$B!!8f3NG'$H>pJs$rM-$jFq$&$4$6$$$^$9!#(B

$B!!$3$N%_%W%7%g%s$K%G%U%)%k%H$G%A%'%C%/$rF~$l$F$_$/!"(B

$B$H8@$&;v$O!"Fq$7$$$N$G$7$g$&$+!#(B

($B:G=i$N0l2s$@$1$_$?$$$G$9$1$l$I$b(B)

$B!!%G%U%)%k%H$G!"%A%'%C%/$rF~$l$FM_$7$$?M$H(B

$BM_$7$/$J$$?M$H!"$I$A$i$,B?$$$+!"$H$+$K5r$j$^$9$,!#(B

$B!!0J>e!"$h$m$7$/$*4j$$CW$7$^$9!#(B

$B!!$G$O!#(B

---

$B:9=P?M(B: Fumio KANEHIRO notifications@github.com
$BAw?.F|;~(B: 2016$BG/(B1$B7n(B5$BF|(B 9:23
$B08@h(B: jvrc/tutorials
CC: $B5\9x@60l(B
$B7oL>(B: Re: [tutorials] $B%A%'%C%/$K$D$$$F(B (#9)

$B4XO"$9$k5DO@$,!"(B
s-nakaoka/choreonoid#50https://github.com/s-nakaoka/choreonoid/issues/50

[https://avatars3.githubusercontent.com/u/845257?v=3&s=400]https://github.com/s-nakaoka/choreonoid/issues/50

$B%b%G%k$rFI$_9~$s$@$i%G%U%)%k%H$GI=<($7$FM_$7$$(B \* Issue #50 \* s-nakaoka/choreonoidhttps://github.com/s-nakaoka/choreonoid/issues/50
github.com
$B8=>u%b%G%k$rFI$_9~$s$G$b%A%'%C%/$rF~$l$J$$$HI=<($5$l$^$;$s$,!"%G%U%)%k%H$G%A%'%C%/$rF~$l$k$h$&$K$9$k$H2?$+ITET9g$"$j$^$9$G$7$g$&$+!#%G%U%)%k%H$GI=<($5$l$?J}$,;H$$>!<j$,$h$$$H;W$&$N$G$9$,!#(B

fkanehiro/choreonoid-editor#2https://github.com/fkanehiro/choreonoid-editor/issues/2
$B$K$"$k$N$G$=$A$i$r8fMw$/$@$5$$!#(B
$B$J$_!"(Bsample3.cnoid$B$r3+$$$F%7%_%e%l!<%7%g%s$,$_$+$7$$$N$O(BBodyRTC$B%"%$%F%`$K%A%'%C%/$,F~$C$F$$$J$$$?$a$G$9!#%A%e!<%H%j%"%k$NK\J8Cf$K$O%A%'%C%/$rF~$l$k$3$H$,=q$$$F$"$k$N$G$9$,!"(Bsample3.cnoid$B$K$=$l$,H?1G$5$l$F$$$J$+$C$?$N$GH?1G$7$F$*$-$^$7$?!#(B

##

**Comment by fkanehiro** [comment]
また化けてしまっているようです。
通知メールの一番下にあるリンクからWebインタフェースに飛んで、Webインタフェースから書き込んでみてはどうでしょうか。

**Comment by smiyakos** [comment]
金広様、

　宮腰です。

　以下、化けてしまったメールでの返信のコピーです。

　御確認と情報を有り難うございます。

　このオプションにデフォルトでチェックを入れておく、
と言う事は、難しいのでしょうか。
(最初の一回だけみたいですけれども)
　デフォルトで、チェックを入れて欲しい人と
欲しくない人と、どちらが多いか、とかに拠りますが。

　以上、よろしくお願い致します。

　では。
